// src/app/features/quiz/word-hint/word-hint.service.ts
import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Observable } from "rxjs";
import { environment } from "../../../../environments/environment";

export interface WordHintCard {
  mongoId: string; // generated by Mongo
  id: number; // your business id
  sentence: string; // correct sentence
  scrambledSentence: string; // words shuffled
  translation: string;
  questionText: string; // displayed prompt
  correctAnswer: string;
  wrongAnswers: string[];
  difficulty: "Easy" | "Medium" | "Hard";
  scoreValue: number;
}

@Injectable({ providedIn: "root" })
export class WordHintService {
  private api = `${environment.apiUrl}/wordhint`; // ↔ /api/wordhint

  constructor(private http: HttpClient) {}

  /** fetch a random batch for the user level */
  getCards(level: string): Observable<WordHintCard[]> {
    const apiLevel = this.toApiLevel(level);
    const num = this.getAmount(level);
    return this.http.get<WordHintCard[]>(
      `${this.api}?level=${apiLevel}&num=${num}`
    );
  }

  /* ---------- helpers ---------------------------------------------------- */
  private toApiLevel(level: string): string {
    switch (level.toUpperCase()) {
      case "BEGINNER":
        return "easy";
      case "INTERMEDIATE":
        return "medium";
      case "ADVANCED":
        return "hard";
      default:
        return "easy";
    }
  }
  private getAmount(level: string): number {
    switch (level.toLowerCase()) {
      case "beginner":
        return 10;
      case "intermediate":
        return 20;
      case "advanced":
        return 30;
      default:
        return 10;
    }
  }
}
